[package]
name = "plitedb"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
libc = { version = "0.2.164", optional = true }
thiserror = "2.0.3"

[features]
ffi = ["dep:libc"]
